# Generated by Django 4.2.3 on 2023-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('alary', models.FloatField()),
                ('education', models.CharField(max_length=128)),
            ],
        ),
    ]
