# Generated by Django 4.2.3 on 2023-12-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsalary',
            old_name='alary',
            new_name='salary',
        ),
    ]
